# Generated by Django 5.2.10 on 2026-01-31 09:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename of the uploaded CSV', max_length=255)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of upload')),
                ('total_records', models.PositiveIntegerField(default=0, help_text='Number of equipment records in this dataset')),
                ('avg_flowrate', models.FloatField(blank=True, help_text='Average flowrate (computed during upload)', null=True)),
                ('avg_pressure', models.FloatField(blank=True, help_text='Average pressure (computed during upload)', null=True)),
                ('avg_temperature', models.FloatField(blank=True, help_text='Average temperature (computed during upload)', null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to stored CSV file', max_length=500, null=True)),
                ('user', models.ForeignKey(help_text='User who uploaded this dataset', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Dataset',
                'verbose_name_plural': 'Equipment Datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Equipment name or identifier', max_length=255)),
                ('equipment_type', models.CharField(help_text='Type/category of equipment', max_length=100)),
                ('flowrate', models.FloatField(help_text='Equipment flowrate parameter')),
                ('pressure', models.FloatField(help_text='Equipment pressure parameter')),
                ('temperature', models.FloatField(help_text='Equipment temperature parameter')),
                ('dataset', models.ForeignKey(help_text='Parent dataset this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analytics.equipmentdataset')),
            ],
            options={
                'verbose_name': 'Equipment Record',
                'verbose_name_plural': 'Equipment Records',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentdataset',
            index=models.Index(fields=['user', '-uploaded_at'], name='analytics_e_user_id_ebbfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentrecord',
            index=models.Index(fields=['dataset', 'equipment_type'], name='analytics_e_dataset_9cdefa_idx'),
        ),
    ]
