# Generated by Django 5.2.10 on 2026-01-31 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_flowrate',
            field=models.FloatField(blank=True, help_text='Average flowrate across dataset', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_pressure',
            field=models.FloatField(blank=True, help_text='Average pressure across dataset', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_temperature',
            field=models.FloatField(blank=True, help_text='Average temperature across dataset', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='file_path',
            field=models.CharField(blank=True, help_text='Optional stored CSV path', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='filename',
            field=models.CharField(help_text='Original CSV filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='total_records',
            field=models.PositiveIntegerField(default=0, help_text='Total number of equipment records'),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Upload timestamp'),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded this dataset', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentrecord',
            name='dataset',
            field=models.ForeignKey(help_text='Parent dataset', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analytics.equipmentdataset'),
        ),
        migrations.AlterField(
            model_name='equipmentrecord',
            name='equipment_type',
            field=models.CharField(help_text='Equipment category/type', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentrecord',
            name='flowrate',
            field=models.FloatField(help_text='Operational flowrate'),
        ),
        migrations.AlterField(
            model_name='equipmentrecord',
            name='pressure',
            field=models.FloatField(help_text='Operational pressure'),
        ),
        migrations.AlterField(
            model_name='equipmentrecord',
            name='temperature',
            field=models.FloatField(help_text='Operational temperature'),
        ),
    ]
