from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.colors import grey

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
file_path = os.path.join(BASE_DIR, "analytics", "demo_reports", "demo_report.pdf")


c = canvas.Canvas(file_path, pagesize=A4)
width, height = A4

# Title
c.setFont("Helvetica-Bold", 22)
c.drawCentredString(width / 2, height - 3 * cm, "ChemViz – Equipment Analytics Report")

# Subtitle
c.setFont("Helvetica", 14)
c.drawCentredString(width / 2, height - 4.2 * cm, "Demo Dataset Summary")

# Body
c.setFont("Helvetica", 12)
text = c.beginText(3 * cm, height - 6 * cm)

content = [
    "Dataset Name: equipment_batch_001.csv",
    "Total Equipment: 156",
    "Average Flowrate: 125.45 units",
    "Average Pressure: 2.87 bar",
    "Average Temperature: 42.3 °C",
    "",
    "Equipment Type Distribution:",
    "- Pumps: 40%",
    "- Valves: 30%",
    "- Reactors: 30%",
    "",
    "This is a demo analytics report generated by ChemViz.",
    "Charts and trends are visualized interactively in the dashboard.",
]

for line in content:
    text.textLine(line)

c.drawText(text)

# Footer watermark
c.setFont("Helvetica-Oblique", 10)
c.setFillColor(grey)
c.drawCentredString(width / 2, 1.5 * cm, "DEMO REPORT – Generated by ChemViz")

c.save()

print("✅ Demo PDF generated:", file_path)
